version: '3.8'

services:
  # Наш первый сервис - База данных Redis
  redis-bank:
    image: redis:latest
    ports:
      - "6379:6379"

  # Наш второй сервис - ML API
  fraud-api:
    build: .             # Говорим Докеру собрать образ из нашего Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - redis-bank       # Указываем, что API нельзя запускать, пока не включится Redis!
    environment:
      - REDIS_HOST=redis-bank # Передаем имя базы данных в наш Python код